{
    pages:
        [ 
            { 
                page_name: 'Home',
                title: 'Home',        
                summary: null,        
                action: 'edited',        
                sha: 'ccb10d0941548b4aa927321e309302f5cb2dfaed',        
                html_url: 'https://github.com/ssyuzev/dj_task_manager/wiki/Home' 
            } 
        ],   
    repository:     
        { 
            id: 130854119,
            name: 'dj_task_manager',
            full_name: 'ssyuzev/dj_task_manager',
            owner:        
                { 
                    login: 'ssyuzev',
                    id: 6229375,         
                    avatar_url: 'https://avatars1.githubusercontent.com/u/6229375?v=4',
                    gravatar_id: '',
                    url: 'https://api.github.com/users/ssyuzev',
                    html_url: 'https://github.com/ssyuzev',
                    followers_url: 'https://api.github.com/users/ssyuzev/followers',
                    following_url: 'https://api.github.com/users/ssyuzev/following{/other_user}',
                    gists_url: 'https://api.github.com/users/ssyuzev/gists{/gist_id}', 
                    starred_url: 'https://api.github.com/users/ssyuzev/starred{/owner}{/repo}',
                    subscriptions_url: 'https://api.github.com/users/ssyuzev/subscriptions',
                    organizations_url: 'https://api.github.com/users/ssyuzev/orgs',
                    repos_url: 'https://api.github.com/users/ssyuzev/repos',
                    events_url: 'https://api.github.com/users/ssyuzev/events{/privacy}',
                    received_events_url: 'https://api.github.com/users/ssyuzev/received_events',
                    type: 'User',
                    site_admin: false 
                },
            private: false,
            html_url: 'https://github.com/ssyuzev/dj_task_manager',
            description: 'Simple prototype of task manager web-application written on Django',
            fork: false,      url: 'https://api.github.com/repos/ssyuzev/dj_task_manager',
            forks_url: 'https://api.github.com/repos/ssyuzev/dj_task_manager/forks',
            keys_url: 'https://api.github.com/repos/ssyuzev/dj_task_manager/keys{/key_id}',
            collaborators_url: 'https://api.github.com/repos/ssyuzev/dj_task_manager/collaborators{/collaborator}',
            teams_url: 'https://api.github.com/repos/ssyuzev/dj_task_manager/teams',
            hooks_url: 'https://api.github.com/repos/ssyuzev/dj_task_manager/hooks',
            issue_events_url: 'https://api.github.com/repos/ssyuzev/dj_task_manager/issues/events{/number}',
            events_url: 'https://api.github.com/repos/ssyuzev/dj_task_manager/events',
            assignees_url: 'https://api.github.com/repos/ssyuzev/dj_task_manager/assignees{/user}',
            branches_url: 'https://api.github.com/repos/ssyuzev/dj_task_manager/branches{/branch}',
            tags_url: 'https://api.github.com/repos/ssyuzev/dj_task_manager/tags',
            blobs_url: 'https://api.github.com/repos/ssyuzev/dj_task_manager/git/blobs{/sha}',
            git_tags_url: 'https://api.github.com/repos/ssyuzev/dj_task_manager/git/tags{/sha}',
            git_refs_url: 'https://api.github.com/repos/ssyuzev/dj_task_manager/git/refs{/sha}',
            trees_url: 'https://api.github.com/repos/ssyuzev/dj_task_manager/git/trees{/sha}',
            statuses_url: 'https://api.github.com/repos/ssyuzev/dj_task_manager/statuses/{sha}',
            languages_url: 'https://api.github.com/repos/ssyuzev/dj_task_manager/languages',
            stargazers_url: 'https://api.github.com/repos/ssyuzev/dj_task_manager/stargazers',
            contributors_url: 'https://api.github.com/repos/ssyuzev/dj_task_manager/contributors',
            subscribers_url: 'https://api.github.com/repos/ssyuzev/dj_task_manager/subscribers',
            subscription_url: 'https://api.github.com/repos/ssyuzev/dj_task_manager/subscription',
            commits_url: 'https://api.github.com/repos/ssyuzev/dj_task_manager/commits{/sha}',
            git_commits_url: 'https://api.github.com/repos/ssyuzev/dj_task_manager/git/commits{/sha}',
            comments_url: 'https://api.github.com/repos/ssyuzev/dj_task_manager/comments{/number}',
            issue_comment_url: 'https://api.github.com/repos/ssyuzev/dj_task_manager/issues/comments{/number}',
            contents_url: 'https://api.github.com/repos/ssyuzev/dj_task_manager/contents/{+path}',
            compare_url: 'https://api.github.com/repos/ssyuzev/dj_task_manager/compare/{base}...{head}',
            merges_url: 'https://api.github.com/repos/ssyuzev/dj_task_manager/merges',
            archive_url: 'https://api.github.com/repos/ssyuzev/dj_task_manager/{archive_format}{/ref}',
            downloads_url: 'https://api.github.com/repos/ssyuzev/dj_task_manager/downloads',
            issues_url: 'https://api.github.com/repos/ssyuzev/dj_task_manager/issues{/number}',
            pulls_url: 'https://api.github.com/repos/ssyuzev/dj_task_manager/pulls{/number}',
            milestones_url: 'https://api.github.com/repos/ssyuzev/dj_task_manager/milestones{/number}',
            notifications_url: 'https://api.github.com/repos/ssyuzev/dj_task_manager/notifications{?since,all,participating}',
            labels_url: 'https://api.github.com/repos/ssyuzev/dj_task_manager/labels{/name}',
            releases_url: 'https://api.github.com/repos/ssyuzev/dj_task_manager/releases{/id}',
            deployments_url: 'https://api.github.com/repos/ssyuzev/dj_task_manager/deployments',
            created_at: '2018-04-24T12:54:22Z',
            updated_at: '2018-04-24T12:55:43Z',
            pushed_at: '2018-04-24T12:54:49Z',
            git_url: 'git://github.com/ssyuzev/dj_task_manager.git',
            ssh_url: 'git@github.com:ssyuzev/dj_task_manager.git',
            clone_url: 'https://github.com/ssyuzev/dj_task_manager.git',
            svn_url: 'https://github.com/ssyuzev/dj_task_manager',
            homepage: '',
            size: 578,
            stargazers_count: 0,
            watchers_count: 0,
            language: 'JavaScript',
            has_issues: true,
            has_projects: true,
            has_downloads: true,
            has_wiki: true,
            has_pages: false,
            forks_count: 0,
            mirror_url: null,
            archived: false,
            open_issues_count: 1,
            license: null,
            forks: 0,
            open_issues: 1,
            watchers: 0,
            default_branch: 'master' 
        },
        sender:
        { 
            login: 'ssyuzev',
            id: 6229375,
            avatar_url: 'https://avatars1.githubusercontent.com/u/6229375?v=4',
            gravatar_id: '',
            url: 'https://api.github.com/users/ssyuzev',
            html_url: 'https://github.com/ssyuzev',
            followers_url: 'https://api.github.com/users/ssyuzev/followers',
            following_url: 'https://api.github.com/users/ssyuzev/following{/other_user}',
            gists_url: 'https://api.github.com/users/ssyuzev/gists{/gist_id}',
            starred_url: 'https://api.github.com/users/ssyuzev/starred{/owner}{/repo}',
            subscriptions_url: 'https://api.github.com/users/ssyuzev/subscriptions',
            organizations_url: 'https://api.github.com/users/ssyuzev/orgs', 
            repos_url: 'https://api.github.com/users/ssyuzev/repos',
            events_url: 'https://api.github.com/users/ssyuzev/events{/privacy}',
            received_events_url: 'https://api.github.com/users/ssyuzev/received_events',
            type: 'User',
            site_admin: false 
        }
} 